# serverless.yml
service: my-portfolio-website
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  styles:
    handler: css.handler
    events:
      - http: ANY /css
      - http: 'ANY /css/{proxy+}'
plugins:
  - serverless-offline